language: go
sudo: false

go:
  - 1.5
  - 1.5.3
  - tip

env:
  - GO15VENDOREXPERIMENT=1

script:
  - go build
  - go vet -v $(go list ./...|grep -v vendor)
  - go test -v $(go list ./...|grep -v vendor)